apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    url: postgres:5432
    database: dev
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable