apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DBNAME}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable

  - name: Redshift
    type: grafana-redshift-datasource
    jsonData:
      authType: keys
      defaultRegion: ${AWS_REGION}
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}