dbt_books_psql:
  outputs:
    dev:
      dbname: {{ env_var('POSTGRES_DBNAME') }}
      host: {{ env_var('POSTGRES_HOST') }}
      pass: {{ env_var('POSTGRES_PASSWORD') }}
      port: {{ env_var('POSTGRES_PORT') }}
      schema: {{ env_var('POSTGRES_SCHEMA') }}
      threads: 2
      type: postgres
      user: {{ env_var('POSTGRES_USER') }}
  target: dev
