{
 "title": "books_dashboard_grafana",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT(country_out) FROM books_schema.dim_country_lut"
   },
   { "name": "num_reviews", "label": "Min. Number of Revies", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Number of Book-Ratings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(1)\nFROM \n    dev.books_schema.stg_ratings;"
    }
   ]
  },
  {
   "title": "Number of Books",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(1)\nFROM \n    books_schema.stg_books;"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(1)\nFROM\n    dev.books_schema.stg_users;"
    }
   ]
  },
  {
   "title": "Top 10 rated books of specified country",
   "type": "table",
   "description": "Country and Min. number of Reviews can be changed. Some countries have very few reviews.",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    ROW_NUMBER() OVER (ORDER BY avg_score DESC) AS \"Rank\",\n    title AS \"Title\",\n    ROUND(avg_score, 2) || ' / 10' AS \"Avg. Rating\",\n    rating_count AS \"Num. Ratings\"\nFROM\n    dev.books_schema.dim_country_book_ratings\nWHERE\n    country = '$country' AND\n    rating_count >= $num_reviews\nORDER BY\n    avg_score DESC\nLIMIT\n    10"
    }
   ]
  },
  {
   "title": "Number of Reviews per age bracket",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT * FROM books_schema.dim_age_ratings"
    }
   ]
  },
  {
   "title": "Top 10 most rating countries",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t*\nFROM\n\tbooks_schema.dim_country_count\nWHERE\n    country IS NOT NULL AND \n\t\tcountry <> 'unknown'\nORDER BY\n\tcount DESC\nLIMIT 10"
    }
   ]
  }
 ]
}