{
 "title": "books_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT country_out FROM books_schema.country_lut;\n"
   },
   { "name": "numreviews", "label": "Min. Number of Revies", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Number of Book-Ratings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT \n    COUNT(1)\nFROM \n    dev.books_schema.stg_ratings_rs;",
     "rawSql": "SELECT\n  COUNT(1)\nFROM\n  books_schema.stg_ratings;"
    }
   ]
  },
  {
   "title": "Number of Books",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT \n    COUNT(1)\nFROM \n    dev.books_schema.stg_books_rs;",
     "rawSql": "SELECT\n  COUNT(1)\nFROM\n  books_schema.stg_ratings;"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT\n    COUNT(1)\nFROM\n    dev.books_schema.stg_users_rs;",
     "rawSql": "SELECT\n  COUNT(1)\nFROM\n  books_schema.stg_users;"
    }
   ]
  },
  {
   "title": "Top 10 rated books of specified country",
   "type": "table",
   "description": "Country and Min. number of Reviews can be changed. Some countries have very few reviews.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSQL": "SELECT\n    ROW_NUMBER() OVER (ORDER BY avg_score DESC) AS \"Rank\",\n    title AS \"Title\",\n    ROUND(avg_score, 2) || ' / 10' AS \"Avg. Rating\",\n    rating_count AS \"Num. Ratings\"\nFROM\n    dev.books_schema.dim_country_book_ratings_rs\nWHERE\n    country = '$country' AND\n    rating_count >= $numreviews\nORDER BY\n    avg_score DESC\nLIMIT\n    10",
     "rawSql": "SELECT\n    ROW_NUMBER() OVER (ORDER BY avg_score DESC) AS \"Rank\",\n    title AS \"Title\",\n    ROUND(avg_score, 2) || ' / 10' AS \"Avg. Rating\",\n    rating_count AS \"Num. Ratings\"\nFROM\n    books_schema.dim_country_book_ratings\nWHERE\n    country = '${country}'\n    AND rating_count >= ${numreviews}\nORDER BY\n    avg_score DESC\nLIMIT\n    10;"
    }
   ]
  },
  {
   "title": "Number of Reviews per age bracket",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "column": "age_bracket",
     "rawSQL": "SELECT \n    * \nFROM \n    dev.books_schema.dim_age_ratings_rs\nORDER BY\n    age_bracket",
     "rawSql": "SELECT \n  * \nFROM \n  books_schema.dim_age_ratings;",
     "schema": "books_schema"
    }
   ]
  },
  {
   "title": "Top 10 most rating countries",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT\n    *\nFROM\n    dev.books_schema.dim_country_count_rs\nWHERE\n    TRIM(COALESCE(country, '')) <> ''\n    AND TRIM(COALESCE(country, '')) <> 'unknown'\nORDER BY\n    count DESC\nLIMIT 10;",
     "rawSql": "SELECT\n    *\nFROM\n    books_schema.dim_country_count\nWHERE\n    country IS NOT NULL\n    AND country <> 'unknown'\nORDER BY\n    count DESC\nLIMIT 10;\n"
    }
   ]
  }
 ]
}